# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0

    steps:
      - checkout
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore ./src
      - run:
          name: "Unit Tests"
          command: dotnet.exe test ./tests/YAJQ.Tests.Unit/YAJQ.Tests.Unit.csproj --no-restore --verbosity normal
      - run:
          name: "Integration Tests"
          command: dotnet.exe test ./tests/YAJQ.Tests.Integration/YAJQ.Tests.Integration.csproj --no-restore --verbosity normal

workflows:
  ci:
    jobs:
      - test
